// Print the code -> Penpot payload, ready to paste into `execute_code`.
//
//   npm run design:push
//
// The Penpot connector runs JavaScript inside a browser tab, which has no
// access to this repository — so the contract cannot be read at the far end and
// has to travel inside the payload. This stitches the two together rather than
// asking anyone to paste a JSON blob into a code file by hand.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');

const contractFile = path.join(root, 'design', 'design.json');
const bodyFile = path.join(root, 'design', 'penpot', 'push.js');

if (!fs.existsSync(contractFile)) {
  console.error(`No contract at ${contractFile} — run \`npm run design:extract\` first.`);
  process.exit(1);
}

const full = JSON.parse(fs.readFileSync(contractFile, 'utf8'));

// Only the parts push.js reads. The lit ladder and the component boxes are the
// larger half of the contract and none of it is pushed — the ladder is
// reproduced in Penpot from the hue and `lit.max` rather than stored. Keeping
// the payload small is not tidiness: an over-long `execute_code` call is the
// thing that drops the plugin connection.
const contract = JSON.stringify(
  {
    themes: {
      light: { tokens: full.themes.light.tokens, type: full.themes.light.type },
      dark: { tokens: full.themes.dark.tokens },
    },
  },
  null,
  2,
);
// The header comment explains the file it lives in, not the payload, and the
// payload is about to be pasted somewhere with no room for it.
const body = fs.readFileSync(bodyFile, 'utf8').replace(/^\/\/[^\n]*\n(?:\/\/[^\n]*\n|\n(?=\/\/))*/, '');

process.stdout.write(`// Generated by \`npm run design:push\` — paste into the Penpot connector.\n`);
process.stdout.write(`const CONTRACT = ${contract};\n\n`);
process.stdout.write(body);
